### YamlMime:YamlDocument
ms.openlocfilehash: 0f5ace1a59293d7cd3f20d15344741fa90b2892c
ms.sourcegitcommit: 8d88a025090e5087b9d0ab390b1207977ef4ff7c
ms.translationtype: HT
ms.contentlocale: es-ES
ms.lasthandoff: 11/21/2018
ms.locfileid: "52276523"
documentType: LandingData
title: Ansible en la documentación de Azure
metadata:
  title: 'Ansible en la documentación de Azure: tutoriales, ejemplos, referencia y recursos'
  description: Aprenda a usar Ansible para automatizar el aprovisionamiento en la nube, la administración de configuración y las implementaciones de aplicaciones.
  ms.service: ansible
  keywords: ansible, azure, devops, tutoriales, ejemplos, referencia
  author: tomarcher
  manager: jeconnoc
  ms.author: tarcher
  ms.topic: landing-page
  ms.date: 08/27/2018
abstract:
  description: Use <a href="http://www.ansible.com">Ansible</a> para automatizar el aprovisionamiento en la nube, la administración de configuración y las implementaciones de aplicaciones.
sections:
- title: Inicios rápidos en 5 minutos
  items:
  - type: paragraph
    text: Instale Ansible y úselo para crear y administrar máquinas virtuales Linux en Azure.
  - type: list
    style: icon48
    items:
    - image:
        src: /azure/media/index/azure_dev-9.svg
      text: Instalación de Ansible
      href: /azure/virtual-machines/linux/ansible-install-configure?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json
    - image:
        src: /azure/media/index/VirtualMachine.svg
      text: Creación de una máquina virtual Linux
      href: /azure/virtual-machines/linux/ansible-create-vm?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json
    - image:
        src: /azure/media/index/VirtualMachine.svg
      text: Administración de una máquina virtual Linux
      href: /azure/virtual-machines/linux/ansible-manage-linux-vm?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json
- title: Tutoriales detallados
  items:
  - type: paragraph
    text: Aprenda a usar Ansible para crear y administrar la infraestructura de procesos, redes y almacenamiento de Azure.
  - type: list
    style: unordered
    items:
    - html: <a href="/azure/virtual-machines/linux/ansible-create-complete-vm?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json">Cree una máquina virtual que incluya una red virtual, una dirección IP pública y una tarjeta adaptadora de la red virtual.</a>
    - html: <a href="./ansible-run-playbook-in-cloudshell">Ejecute Ansible con Bash en Azure Cloud Shell.</a>
    - html: <a href="./ansible-manage-azure-dynamic-inventories">Cree y administre un inventario dinámico de sus recursos de Azure.</a>
    - html: <a href="./ansible-create-configure-vmss">Cree y administre conjuntos de escalado de máquinas virtuales en Azure.</a>
    - html: <a href="./ansible-deploy-app-vmss">Implemente aplicaciones en conjuntos de escalado de máquinas virtuales de Azure.</a>
    - html: <a href="./ansible-create-configure-aks">Cree y administre clústeres de Azure Kubernetes Service.</a>
    - html: <a href="./ansible-create-configure-application-gateway">Administración del tráfico web con una instancia de Azure Application Gateway</a>.
- title: Referencia
  items:
  - type: list
    style: cards
    className: cardsD
    items:
    - title: Roles de guión de procedimientos
      html: <p><a href="https://galaxy.ansible.com/Azure/azure_preview_modules/">azure_preview_module</a></p>
    - title: Versiones y características
      html: <p><a href="./ansible-matrix.md">Matriz de características de los módulos y roles</a></p>
    - title: Herramientas
      html: <p><a href="https://marketplace.visualstudio.com/items?itemName=vscoss.vscode-ansible">Extensión de Visual Studio Code para Ansible</a></p>
